# Rarity mapping: item_name -> (rarity_name, rarity_icon_file, sheckle_cost)

rarity_data = {
    # Seeds
    "Carrot": ("Common", "CommonTier.jpg", 10),
    "Strawberry": ("Common", "CommonTier.jpg", 50),
    "Blueberry": ("Uncommon", "UncommonIcon.png", 400),
    "Orange Tulip": ("Uncommon", "UncommonIcon.png", 600),
    "Tomato": ("Rare", "RareIcon.png", 800),
    "Corn": ("Rare", "RareIcon.png", 1300),
    "Daffodil": ("Rare", "RareIcon.png", 1000),
    "Watermelon": ("Legendary", "LegendaryIcon.png", 2500),
    "Pumpkin": ("Legendary", "LegendaryIcon.png", 3000),
    "Apple": ("Legendary", "LegendaryIcon.png", 3250),
    "Bamboo": ("Legendary", "LegendaryIcon.png", 4000),
    "Coconut": ("Mythical", "Mythical_Icon.png", 6000),
    "Cactus": ("Mythical", "Mythical_Icon.png", 15000),
    "Dragon Fruit": ("Mythical", "Mythical_Icon.png", 50000),
    "Mango": ("Mythical", "Mythical_Icon.png", 100000),
    "Grape": ("Divine", "Divine.png", 850000),
    "Mushroom": ("Divine", "Divine.png", 150000),
    "Pepper": ("Divine", "Divine.png", 1000000),
    "Cacao": ("Divine", "Divine.png", 2500000),
    "Beanstalk": ("Prismatic", "PrismaticTier.gif", 10000000),
    "Ember Lily": ("Prismatic", "PrismaticTier.gif", 15000000),
    "Sugar Apple": ("Prismatic", "PrismaticTier.gif", 25000000),
    "Burning Bud": ("Prismatic", "PrismaticTier.gif", 40000000),
    "Giant Pinecone": ("Prismatic", "PrismaticTier.gif", 55000000),
    "Elder Strawberry": ("Prismatic", "PrismaticTier.gif", 70000000),

    # Eggs
    "Common Egg": ("Common", "CommonTier.jpg", 0),
    "Uncommon Egg": ("Uncommon", "UncommonIcon.png", 0),
    "Rare Egg": ("Rare", "RareIcon.png", 0),
    "Legendary Egg": ("Legendary", "LegendaryIcon.png", 0),
    "Mythical Egg": ("Mythical", "Mythical_Icon.png", 0),
    "Bug Egg": ("Special", "Divine.png", 0),

    # Gear
    "Watering Can": ("Rare", "RareIcon.png", 50000),
    "Trowel": ("Rare", "RareIcon.png", 100000),
    "Recall Wrench": ("Rare", "RareIcon.png", 150000),
    "Basic Sprinkler": ("Common", "CommonTier.jpg", 25000),
    "Advanced Sprinkler": ("Uncommon", "UncommonIcon.png", 50000),
    "Godly Sprinkler": ("Rare", "RareIcon.png", 120000),
    "Master Sprinkler": ("Rare", "RareIcon.png", 10000000),
    "Grandmaster Sprinkler": ("Prismatic", "PrismaticTier.gif", 1000000000),
    "Cleaning Spray": ("Uncommon", "UncommonIcon.png", 15000000),
    "Favorite Tool": ("Rare", "RareIcon.png", 20000000),
    "Harvest Tool": ("Rare", "RareIcon.png", 30000000),
    "Friendship Pot": ("Uncommon", "UncommonIcon.png", 15000000),
    "Magnifying Glass": ("Rare", "RareIcon.png", 10000000),
    "Medium Treat": ("Uncommon", "UncommonIcon.png", 4000000),
    "Medium Toy": ("Uncommon", "UncommonIcon.png", 4000000),
    "Level Up Lollipop": ("Rare", "RareIcon.png", 10000000000),
}
